{"name": "Проверка ошибки при авторизации с неверным полем логин", "status": "passed", "steps": [{"name": "Логин курьера в систему", "status": "passed", "parameters": [{"name": "data", "value": "{'login': ('darlene11', '#bmNoiDoA4'), 'password': '23432'}"}], "start": 1714855183492, "stop": 1714855184176}, {"name": "Проверка статуса и текста", "status": "passed", "parameters": [{"name": "code", "value": "404"}, {"name": "name", "value": "'message'"}, {"name": "text", "value": "'Учетная запись не найдена'"}], "start": 1714855184176, "stop": 1714855184176}], "start": 1714855183492, "stop": 1714855184178, "uuid": "37cd3059-ad83-46f0-b864-a907fdd8213b", "historyId": "90a1c805a52ac04362cdf4f8fe7dd316", "testCaseId": "90a1c805a52ac04362cdf4f8fe7dd316", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_auth_login_field_wrong", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Sasaraf"}, {"name": "thread", "value": "16480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}